name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version of the application to deploy"
        required: false
        default: "latest"
        type: string

jobs:
  manual-trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display input values
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"

      - name: Run deployment steps
        run: |
          if [ "${{ inputs.environment }}" == "production" ]; then
            echo "Running deployment for PRODUCTION environment!";
          # Add production-specific deployment commands here
          elif [ "${{ inputs.environment }}" == "staging" ]; then
            echo "Running deployment for STAGING environment!";
          # Add staging-specific deployment commands here
          fi

 #     - name: Run deployment steps
 #       if: ${{ inputs.environment == 'production' }}
 #       run: echo "Running deployment for PRODUCTION environment!"

 #     - name: Run deployment steps for staging
 #       if: ${{ inputs.environment == 'staging' }}
 #       run: echo "Running deployment for STAGING environment!        
